<?php
/**
 * Status template
 *
 * @category SMSAPI
 * @package  Smsapi|SMSAPI
 * @author   Paweł Detka <pawel.detka@monogo.pl>
 */

use Smsapi\Smsapi2\Block\Adminhtml\System\Config\Status;

?>
<?php
/**
 * @var $block Status
 */
?>
<style>
    .accordion .config .label {
        width: 15% !important;
    }

    .accordion .config .value {
        width: 85% !important;
    }
</style>

<?php if ($block->isOauthEnabled() && empty($block->isBearerSet())): ?>

<button id="oauth" title="<?= __('OAuth Login') ?>" type="button"
        class="action-default scalable primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
        data-ui-id="page-actions-toolbar-save-button" role="button" aria-disabled="false"
        onclick="window.open('<?= $block->getOauthUrl() ?>')">
            <span class="ui-button-text">
               <span><?= __('OAuth Login') ?></span>
            </span>
</button>

<?php elseif (!$block->isValid() && $block->isTokenEnabled()): ?>
    <div class="smsapi_system_status_container_register">
        <button id="gotodashboard" title="<?= __('Go to SMSAPI dashboard') ?>" type="button"
                class="action-default scalable primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                data-ui-id="page-actions-toolbar-save-button" role="button" aria-disabled="false"
                onclick="window.open('https://www.smsapi.pl/rejestracja')">
            <span class="ui-button-text">
               <span><?= __('Register in SMSAPI') ?></span>
            </span>
        </button>

    </div>
<?php elseif (empty($block->getProfile()) || !empty($block->getErrors())): ?>

    <?php foreach ($block->getErrors() as $error): ?>
        <div class="smsapi_system_status_container">
            <span style="font-weight: bold; color:red"> <?= __($error) ?> </span><br/>
        </div>
    <?php endforeach; ?>

<?php else: ?>

    <?php $profile = $block->getProfile(); ?>
    <div class="smsapi_system_status_container">
        <button id="oauth" title="<?= __('Logged In with OAuth') ?>" type="button" style="background:green; border:green"
                class="action-default scalable primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                data-ui-id="page-actions-toolbar-save-button" role="button" aria-disabled="false"
                onclick="window.open('<?= $block->getOauthUrl() ?>')">
            <span class="ui-button-text">
               <span><?= __('Logged In with OAuth') ?></span>
            </span>
        </button>
        <br>
        <span style="font-weight: bold; color:green"> <?= __('Account') ?>: </span><span><?= $profile->name ?></span><br/>
        <span style="font-weight: bold; color:green"> <?= __('Points') ?>: </span><span><?= $profile->points ?></span><br/>
        <span><a href="https://ssl.smsapi.pl/" target="_blank">ssl.smsapi.pl</a></span><br/>

        <?php if (!$block->isOauthEnabled()): ?>

            <button id="gotodashboard" title="<?= __('Go to SMSAPI dashboard') ?>" type="button"
                class="action-default scalable primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                data-ui-id="page-actions-toolbar-save-button" role="button" aria-disabled="false"
                onclick="window.open('https://ssl.smsapi.<?= $block->getService() ?>/react/oauth/manage')">
            <span class="ui-button-text">
               <span><?= __('To generate key click here') ?></span>
            </span>
        </button>
        <?php endif; ?>


    </div>

<?php endif; ?>

<script>
    require(['jquery'], function ($) {
        var service = '<?= $block->getService()?>';
        var href = "window.open('https://ssl.smsapi.xxx/sms_settings/sendernames/')";
        $("#senders_comment").attr("onclick", href.replace('xxx', service)).css("font-weight", "bold");
    });
</script>
