<?php
/**
 * Status template
 *
 * @category SMSAPI
 * @package  Monogo|SMSAPI
 * @author   Paweł Detka <pawel.detka@monogo.pl>
 */
?>
<?php
/**
 * @var $block \Monogo\Smsapi\Block\Adminhtml\System\Config\Status
 */
?>
    <style>
        .accordion .config .label {
            width: 15% !important;
        }

        .accordion .config .value {
            width: 85% !important;
        }
    </style>

<?php if (!$block->isValid()): ?>
    <div class="smsapi_system_status_container_register">
        <button id="gotodashboard" title="<?= __('Go to SMSAPI dashboard') ?>" type="button"
                class="action-default scalable primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                data-ui-id="page-actions-toolbar-save-button" role="button" aria-disabled="false" onclick="window.open('https://www.smsapi.pl/rejestracja')">
            <span class="ui-button-text">
               <span><?= __('Register in SMSAPI') ?></span>
            </span>
        </button>
    </div>
<?php elseif (empty($block->getProfile()) || !empty($block->getErrors())): ?>

    <?php foreach ($block->getErrors() as $error): ?>
        <div class="smsapi_system_status_container">
            <span style="font-weight: bold; color:red"> <?= __($error) ?> </span><br/>
        </div>
    <?php endforeach; ?>

<?php else: ?>

    <?php $profile = $block->getProfile(); ?>
    <div class="smsapi_system_status_container">
        <span style="font-weight: bold; color:green"> <?= __('Account') ?>: </span><span><?= $profile->name ?></span><br/>
        <span style="font-weight: bold; color:green"> <?= __('Points') ?>: </span><span><?= $profile->points ?></span><br/>
        <span><a href="https://ssl.smsapi.pl/"></a></span><br/>
        <button id="gotodashboard" title="<?= __('Go to SMSAPI dashboard') ?>" type="button"
                class="action-default scalable primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                data-ui-id="page-actions-toolbar-save-button" role="button" aria-disabled="false" onclick="window.open('https://ssl.smsapi.pl/')">
            <span class="ui-button-text">
               <span><?= __('Go to SMSAPI dashboard') ?></span>
            </span>
        </button>
    </div>

<?php endif; ?>